replicaCount: 1

image:
  repository: errm/cheese
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "cheddar"

nameOverride: "cheddar"

service:
  type: NodePort
  port: 80
  nodePort: 31001

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: cheddar.sti.ufpb.br
      paths:
        - path: /
          pathType: Prefix
#  tls:
#    - secretName: wildcard-sti
#      hosts:
#        - cheddar.sti.ufpb.br
